### ISSUE TITLE
играть криминальная ксена бесплатно без регистрации и смс 2$ в час только сегодня

### ISSUE THREAD

**Issue by DeVerezzer** [animusdev/green#103]
Такое дело - соснул, пока ждал очереди на клонирование - заметил улей ксен. Там было около двух макак под лицеебами. Тыкал кнопочку "Да", но меня ролью не делало. При этом этими окошками спамило пиздец как. В итоге алиен был весь раунд один, хоть заразил человек ~10. Банально не кидало за личинок, даже если тыкать "Да"

**Comment by AlexSPN** [comment]
https://github.com/animusdev/green/commit/af930e216f8af296e06942736ead6b8d85aa80bd
