### ISSUE TITLE
Застрелиться быстро

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#114]
Сменить механику клика по СВОЕМУ рту оружием.
После первого клика отображается "Иван Пупкин вставил %оружие% в свой рот", а после второго - выстрел. Отменяется все после смены руки, убирания оружия, стана, и так далее. Это позволит как полчаса угрожать застрелиться, так и застрелиться сразу, резко и безостановочно. А то сейчас пока прождешь - на тебя накинутся и пушку отберут.

**Comment by Stritirok** [comment]
Да и стрельнуть кому нибудь в рот тоже долго. Ужасно долго.
