### ISSUE TITLE
Дроны и их мучения

### ISSUE THREAD

**Issue by silentenemy** [animusdev/green#118]
Дроны не могут поднимать вещи.

**Comment by Euronem** [comment]
дроны должны страдать, как и гостота

**Comment by Phantom-dem** [comment]
Из-за этого они ремонтировать станцию не могут. Сейчас они бесполезны.

**Comment by Euronem** [comment]
пиздуй работать лентяй

**Comment by AlexSPN** [comment]
[Фикшено](https://github.com/animusdev/green/commit/98efbdb436be35dc314ded1e9d70dd9f6a08351d)
