### ISSUE TITLE
Портал в Нарнию

### ISSUE THREAD

**Issue by DeVerezzer** [animusdev/green#124]
Положил тело на трехтайловый стол на кухне (на середину). Флипнул стол. ТЕЛО ПЕРЕНЕСЛО В НАРНИЮ. Больше это тело я не видел вообще, возможно, оно попало в лучший мир где нет робаста и огнетушителя, а возможно его просто удалило.

**Comment by Euronem** [comment]
Тестил с Сайлентом. Багу не словил.

**Comment by Euronem** [comment]
возможно, проблема в Вас.

**Comment by silentenemy** [comment]
При таком раскладе труп просто падает под стол, где его не видно.
Не ебитесь в глаза, пожалуйста.
![Не ебись в глаза](http://puu.sh/oBoDk/bc52752a09.png)
