### ISSUE TITLE
Внеземные технологии нюкеров или нерфоцирк

### ISSUE THREAD

**Issue by DeVerezzer** [animusdev/green#125]
Бомбу нюкеров невозможно уничтожить даже штучками из аплинка, когда отпиздить этих же нюкеров, а еще ТЕЛЕСАЕНС НЕ МОЖЕТ ТЕЛЕПОРТИРОВАТЬ БОМБУ, ОХУЕТЬ, ДА.

**Comment by ucnaHez** [comment]
Телесаенс прекрасно телепортирует бомбу туда-сюда, а уничтожать ее никогда нельзя было, ибо нефиг. Диск ищи.
/close
