### ISSUE TITLE
Предложения по улучшению

### ISSUE THREAD

**Issue by Vasenatr** [animusdev/green#128]
Предлагаю:
1). Диспенсеры в бар.
2). Железные тела (Аугументация или метализация) для роботистов сразу в начале игры.
3). Несколько кубов "ММИ для призраков" в начале игры роботистам.
4). Плавующий лимит на асистентов, в зависимости от присутствующего персонала.

**Comment by Euronem** [comment]
нет 
охуенно, аирон мэны с абсорбом 80% брута с начала игры. Нет 
это еще ладно, можно посмотреть  
нет

**Comment by Vasenatr** [comment]
Чем вам диспенсеры не угодили? Без них коктели заипёшся варить....
Ну так то 80% бруто в начале не оч хорошо, но очень обидно что для метализации нужен напарник... Пока это дело можно было самому себе было афигенно, а теперь...
пропуск
Почему нет? были раунды, где 8 асистентов и 0 инженеров... Было печально.

**Comment by ucnaHez** [comment]
Диспенсеры - не тру, спокойно можно варить коктейли в шейкере или стакане, причем чисто.

Иди нахуй, ты еще диспенсер кислоты РнДшникам приделай. ВЗАИМОДЕЙСТВУЙ В ИГРЕ ПРО ВЗАИМОДЕЙСТВИЕ.

А про ассистентов - туда же, нахуя? Что такого, что восемь ассистух и ноль инженеров? Если человек хочет играть за ассистента, а он заблокирован - он не пойдет за инженера, он пойдет в другую игру или за капелана.

**Comment by Euronem** [comment]
Испанец все сказал за меня. Ждем мнения других кодеров.

**Comment by Invaser777** [comment]
Ты не понимаешь СУТИ. Это всё делает ССку пиздец казуальной. Что-то вроде раздатчиков мутагена в гидропонике, или что-то подобное убирает весь фан. Почему РнД еще не запилили свою шахтерку? А потому что взаимодействие между игроками и влияние действий одних на других.
