### ISSUE TITLE
Баг с экстрактом слайма

### ISSUE THREAD

**Issue by Pizhik** [animusdev/green#129]
Admin PM from-Administrator: Тогда, вполне возможно, баг. Опиши на гитхабе во всех подробностях - может, пофиксят

Задание #3: Украдите неиспользованный экстракт слайма. Провал.
В общем. Пропустил слайма через слаймпроцессор, положил 'blue slime extract' в рюкзак, и задание не засчитало.

**Comment by Euronem** [comment]
посмотрю.

**Comment by Smalltasty** [comment]
С серым экстрактом баг не детектится. Надо будет пробовать с другими.

**Comment by Pizhik** [comment]
Попробуй сначала охладить его

**Comment by Euronem** [comment]
Багу ни я, ни Алина не поймали.
