### ISSUE TITLE
Инструкция к шлемам скафандров

### ISSUE THREAD

**Issue by Dark-Magov** [animusdev/green#132]
В очередной раз наблюдая инженера, не знающего о выдвижном шлеме, мне подумалось что с этим надо что-то сделать.

Почему-бы не запихать в хранилища инженерных и шахтёрских скафандров на место шлема короткую записку о том что шлем ныне встроен в сам скафандр?

**Comment by Stritirok** [comment]
Может плакат на стену сделать? Ну как там вот эти огромные штуки НЕ КУРИТЬ, РАДИАЦИЯ и прочее.

**Comment by Dark-Magov** [comment]
> Может плакат на стену сделать? Ну как там вот эти огромные штуки НЕ КУРИТЬ, РАДИАЦИЯ и прочее.

"DON'T FORGET TO RISE YOUR HELMET?"
Вообще, если нарисуешь, можно наверное и плакатом сделать.

**Comment by Stritirok** [comment]
Понял, шеф.

**Comment by Stritirok** [comment]
http://rgho.st/private/7jtjRPYnG/613751b91b4c9c3a6182772cac1b0f06

Ну я сделал это так, нормально?

**Comment by Dark-Magov** [comment]
> http://rgho.st/private/7jtjRPYnG/613751b91b4c9c3a6182772cac1b0f06

> Ну я сделал это так, нормально?

Ну, выглядит неплохо, но как-то не слишком очевидно что они выдвигающиеся.

**Comment by Euronem** [comment]
Добавлю инструкцию в экзамайн ригов как доберусь до ПК.
