### ISSUE TITLE
Эмоутопроблемы

### ISSUE THREAD

**Issue by Dark-Magov** [animusdev/green#145]
HELP: EditorRUS/(Atarabashi Nihondzin) (?) (PP) (VV) (SM) (JMP) (TP) : А баг со сломанными эмоутами так и не пофиксили
Admin PM to-EditorRUS/(Atarabashi Nihondzin): сигнал - 1 уже видел.
Admin PM to-EditorRUS/(Atarabashi Nihondzin): Какой?
HELP: EditorRUS/(Atarabashi Nihondzin) (?) (PP) (VV) (SM) (JMP) (TP) : Должно быть raises 1 finger
HELP: EditorRUS/(Atarabashi Nihondzin) (?) (PP) (VV) (SM) (JMP) (TP) : Эмоуты динамические сломаны
HELP: EditorRUS/(Atarabashi Nihondzin) (?) (PP) (VV) (SM) (JMP) (TP) : От русика вашего ебаного небось

А ещё *salute отдаёт честь.

**Comment by fluorescent-net** [comment]
>А ещё *salute отдаёт честь.

И что не так?

**Comment by fluorescent-net** [comment]
https://github.com/animusdev/green/pull/146
