### ISSUE TITLE
HELP: AlexDc546/(alien drone (544)) (?) (PP) (VV) (SM) (JMP) (TP) : >You try to get up, but you can't because you have no legs.

### ISSUE THREAD

**Issue by Euronem** [animusdev/green#148]
HELP: AlexDc546/(alien drone (544)) (?) (PP) (VV) (SM) (JMP) (TP) : >You try to get up, but you can't because you have no legs.

**Comment by Euronem** [comment]
работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука

**Comment by Euronem** [comment]
работай сука работай сука работай сука работай сука работай сукаработай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука  работай сука работай сука

**Comment by Euronem** [comment]
работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука работай сука

**Comment by AlexSPN** [comment]
https://github.com/animusdev/green/commit/a5ca9ff00fbee38833e2fa1fb217e243fdde81c5
