### ISSUE TITLE
Ваш блюспейс мусорный мешок - хуета

### ISSUE THREAD

**Issue by ThisIsADVOKAT** [animusdev/green#152]
То что в него можно бесконечно ложить мусор это хорошо, но он стоит ресурсов, а за это мы получаем обычный мусорный мешок, ибо на станции с трудом наберется полный мешок мусора. Я не прошу делать из мешка - рюкзак, но сделайте что-нибудь, а пока этот мешок - трата ресурсов.

**Comment by Plastmassa** [comment]
>То что в него можно бесконечно ложить мусор это хорошо
На этом и закончим.

**Comment by ThisIsADVOKAT** [comment]
В него даже пруты не лезут.

**Comment by fluorescent-net** [comment]
Надо запилить заплечный мешок из мусорного мешка и куска ткани/провода. И из обычного, и из этого. Космобомжи!
Нужен только классный бомжацкий спрайт.

**Comment by Dark-Magov** [comment]
> на станции с трудом наберется полный мешок мусора.

Просто ты не умеешь собирать мусор.

**Comment by Plastmassa** [comment]
>Надо запилить заплечный мешок из мусорного мешка и куска ткани/провода

Нечто подобное есть в донат панели как "santa bag" или вроде того.
