### ISSUE TITLE
Детективопроблемы

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#156]
- [x] Нумбер ван. Вместилище в шляпе. При старте в ней не видно находящейся там фляжки, и ее не вытащить. Каким-то образом она прорисовывается позже.
- [ ] Нумбер ту. Перетащили кобуру на новый слот - ладно. Но его же не видно при свернутом инвентаре! Надо с этим что-то сделать. -

**Comment by ucnaHez** [comment]
Первое фиксится открыванием шляпки перетаскиванием, а не кликом, как делать апдейт инвентаря кодом - без понятия.

**Comment by fluorescent-net** [comment]
Я вполне специально сделал кобуру в той части интерфейса, которая сворачивается, потому что в основном там бижутерия и прочие бандольеры, которые быстрого доступа не требуют. Надо просто сделать выхватывание ствола по клику на кобуру, без залезания в контейнер.
