### ISSUE TITLE
Спрайты русских букв, написанных мелком/баллончиком на полу.

### ISSUE THREAD

**Issue by Dark-Magov** [animusdev/green#161]
Reply PM from-Alsarim/(Huffie Easter): Хули до сих пор не нарисовали руснявого шрифта для мелков? Это делает меня грустить

**Comment by Stritirok** [comment]
Вот. http://rgho.st/private/7BvKBtsR4/45368596b08776765a529902359c480e

**Comment by silentenemy** [comment]
Запилено.
