### ISSUE TITLE
Auld Laser

### ISSUE THREAD

**Issue by Deadr0x** [animusdev/green#162]
При стрельбе из старого лазера, что добывается в гейтвее, отображается, якобы стреляли из пристрелочного.

You fire Old laser!
Security Cyborg-987 is hit by a practice laser in the head!

**Comment by ucnaHez** [comment]
Ето так в коде и запилено. Тамошний кепский ретролазер разнерфали (хотя и не мы), а олдлазеры - подкласс практислазеров.
/obj/item/weapon/gun/energy/laser/practice/sc_laser
    name = "Old laser"

**Comment by ucnaHez** [comment]
Кстати, почините на том гейтвее сейф. Бумажки с кодом спавнят пятизначный код, а сейфы у нас работают на трехзначном -> сейф открыть только взломом.
