### ISSUE TITLE
Термоэлектрический генератор #2

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#185]
Его никто не починил, создать все еще нельзя, спавн все еще не вызывает initialize(), открыть закрытый тикет нельзя.

Если кто до сих пор не понял, о чем я гоорю - я говорю о ТЭГе, ![baylunastep4](https://cloud.githubusercontent.com/assets/9585826/16906711/1c8e0074-4cde-11e6-9587-7bcb68744b7b.png)

**Comment by ucnaHez** [comment]
![baylunastep4](https://cloud.githubusercontent.com/assets/9585826/16906711/1c8e0074-4cde-11e6-9587-7bcb68744b7b.png)

**Comment by fluorescent-net** [comment]
Переоткрыл предыдущий.
