### ISSUE TITLE
Убрать лишнюю нижнюю одежду

### ISSUE THREAD

**Issue by john9911** [animusdev/green#20]
Не нужны эти сотни маек уровня серп@молот и "ялюблюнт" да радужных чулков. Оставить только трусы/лифаны разных цветов и все, не нужна лишняя спрайторабота. И проще будет, если _когда-нибудь_ начнем портировать тонкотрапов.

**Comment by ucnaHez** [comment]
Ета

Надо это делать? Их правда очень дофига.
