### ISSUE TITLE
Немного неприятностей с алиенами

### ISSUE THREAD

**Issue by jammer312** [animusdev/green#200]
~~1. Когда ломаешь алиеном АПЦ, взломанный малфом, у него спрайт не меняется.~~
2. Когда квина плюется нейротоксином, она не отлетает от него в противоположную сторону (а должна бы)
3. Алиены не могут ломать турели. Вместо этого они пытаются их настраивать и лажают из-за проблем с меткостью.

**Comment by jammer312** [comment]
Примечание к пункту 2. : имелась ввиду стрельба при полете по космосу ( по идее нейротоксин должен давать возможность маневрирования по космосу (хоть и убогую и ограниченную 10 выстрелами))

**Comment by Euronem** [comment]
> Алиены не могут ломать турели. Вместо этого они пытаются их настраивать и лажают из-за проблем с меткостью.

**Comment by Euronem** [comment]
лол

**Comment by jammer312** [comment]
Примечание к пункту 1. : судя по всему, это не только на алиенов распространяется, поэтому следует исключить его из списка.
