### ISSUE TITLE
Верни алиенов как режим!

### ISSUE THREAD

**Issue by qwertyon** [animusdev/green#216]
Верни алиенов как режим! Как событие, никогда не происходит, нужен такой режим!

**Comment by silentenemy** [comment]
Как рандомивонт - есть, и этого достаточно.

**Comment by Plastmassa** [comment]
Да

**Comment by Euronem** [comment]
http://screencrush.com/442/files/2015/02/duck-tales-reboot-pic.jpg?w=720&cdnnode=1

**Comment by MyLittleLoly** [comment]
![](https://pp.vk.me/c637529/v637529478/5d7b/H9MUhzNxAWA.jpg)
