### ISSUE TITLE
Безрукие могут брать предметы

### ISSUE THREAD

**Issue by Mioru** [animusdev/green#220]
Персонаж с ампутированными руками может брать предметы. Вроде, даже дизарм без рук тоже работает. Также на безруких всё ещё можно надевать наручники. С кандалами у безногих, вероятно, такая же проблема.

**Comment by fluorescent-net** [comment]
#211

**Comment by Euronem** [comment]
юра, блядь

**Comment by fluorescent-net** [comment]
Таска была открыта в день правки до обновления сервера. Найс дупликейт.
