### ISSUE TITLE
IED

### ISSUE THREAD

**Issue by SneakBug8** [animusdev/green#231]
IED не работает. Никак.
Только отбрасывает объекты, но 1) не поджигает 2) не наносит урон игрокам

**Comment by jammer312** [comment]
Совсем недавно поджигал. Урон наносить не должен, он зажигательный(то есть должен, но косвенно). Отбрасывать тоже не должен.

**Comment by SneakBug8** [comment]
Она вообще ничего не делала. Стояли 4 фуелтанка, дык она их не взорвала. Когда кинул еще одну на кухню, то она только отбросила предмет, лежавший на том же тайле, что и бомба.

**Comment by fluorescent-net** [comment]
Иед ёбаное говнище, требует переработки уже давно.
