### ISSUE TITLE
Мехи не могу заходить в воронки, порталы

### ISSUE THREAD

**Issue by jammer312** [animusdev/green#235]
Может это и не баг, но т.к. рипли не может зайти в воронку, которую создает генератор воронок, полезность этого генератора сильно падает.

**Comment by jammer312** [comment]
Насчет порталов от ручного телепортера не уверен, но от стационарного могут(только что проверил). В воронки не могут.

**Comment by jammer312** [comment]
В портал от ручного телепортера войти не могут

**Comment by Euronem** [comment]
пиздарики тг-шники понерфили

**Comment by jammer312** [comment]
Вообще, это был ненамеренный нерф(т.е. мехи должны телепортироваться, но код работает не так, как надо).
