### ISSUE TITLE
Холодильник

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#245]
Анекдот.

Хотя нет, я тут не за этим.

Холодильник не перенесли с НТ, критический баг!
Он не защищает от ядреной бомбы!

**Comment by Qwertyon666** [comment]
Я в танке, что за холодильник?

**Comment by ucnaHez** [comment]
Чо, холодильника на станции не видел?
http://s00.yaplakal.com/pics/pics_original/1/8/3/6562381.jpg

**Comment by Qwertyon666** [comment]
Неа, говорю же, я в танке
