### ISSUE TITLE
Адаптация Меме для ТГ как мидлраунд

### ISSUE THREAD

**Issue by Qwertyon666** [animusdev/green#246]
Перенос Меме в ТГ. Вырезан, так как не годился как основной режим, но сойдет для ивонта.
Кодить там совсем немного, но я никак не могу разобраться с гитом и пока все медленно делаю, по-этому поднимаю эту тему здесь.

**Comment by Euronem** [comment]
А зачем он нужен?

**Comment by ucnaHez** [comment]
Ну как. Иногда мемо был веселый, а если юзать его как мидраундового - то вообще будет хорошо. Ролька-то интересная, если подумать.

**Comment by dosiozborn** [comment]
И в правда

**Comment by elspark10101** [comment]
Было бы хорошо
