### ISSUE TITLE
Сломанные спрайты

### ISSUE THREAD

**Issue by Mioru** [animusdev/green#247]
Уже очень долго сломаны спрайты подменов. Больше двух месяцев точно.
Спрайты големов и шэдоулингов, вроде бы, поломаны тоже.
Вот так выглядит подмен: http://s018.radikal.ru/i512/1609/a4/fa70da412770.png
Будучи полностью раздетым, он вообще невидим. Видны только глаза. А при повороте спиной не видно уже и их. Из-за чего в рукопашном бою для персонала без всяких ХУДов он становится почти неуязвим, так как по нему просто никак не кликнуть. 
Невидимкой быть весело, но всё же оно ведь не так задумывалось.

А ещё этот баг с вечной красной рукой тоже до сих пор не починен: https://github.com/animusdev/green/issues/130

**Comment by silentenemy** [comment]
Спрайты рас починены, закрываю во избежание дубликатов.
