### ISSUE TITLE
Детективам - рольки!

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#248]
СБ-то без ролек отлично живет, а вот детективу триторка не помешает. Ведь все же способ получить нормальный револьвер, ПОДДЕЛЫВАНИЯ УЛИК и прочее веселье.

**Comment by Qwertyon666** [comment]
И как объяснить что нет-нет, да детектив тритор не смотря на имплант лояльности?

**Comment by ucnaHez** [comment]
И чо? Все знают, что импланты лояльности на триторки не влияют, Синдикат умел их ВЗЛАМЫВАТЬ. Единственное, что они могут - удерживать натиск лолфлеша и культомагии.

А если хочется прям пиздецкаких имплантов ЛОЯЛЬНОСТИ, то детективу можно оный отрезать.

**Comment by Seldorne** [comment]
Давать детективу задание на выполнение плана по раскрытию уголовных дел. Месячные нормы за один раунд.

**Comment by ucnaHez** [comment]
Пилить?

**Comment by fluorescent-net** [comment]
@ucnaHez 
Да, давай.
