### ISSUE TITLE
Ивонт: Проклятый топор

### ISSUE THREAD

**Issue by Qwertyon666** [animusdev/green#251]
Ивонт. Где-то на станции появляется проклятый топор, отличается от обычного только спрайтом.
Тот кто берет топор превращается в убийцу (Вурхиз, Крик или кто-то еще) получает плюшки и задание на убийство всего экипажа/покинуть станцию на шаттле в одиночку.
UPD
Фишка в том, что тот кто убивает убийцу, сам становится убийцей - получает те же плюшки и то же задание

**Comment by silentenemy** [comment]
почему у нас нет плашки о пробитии дна?

**Comment by Qwertyon666** [comment]
Бля
Я забыл самую главную фишку

**Comment by fluorescent-net** [comment]
ГРОБ ГРОБ КРЕМАТОРИЙ СВАРЩИК
