### ISSUE TITLE
ААААААААА!(с)

### ISSUE THREAD

**Issue by Qwertyon666** [animusdev/green#256]
Без понятия как это сделать по канону, но все же
![image](https://cloud.githubusercontent.com/assets/22128752/18956935/e883a1b4-8665-11e6-9513-c4a60a88ad5d.png)
![image](https://cloud.githubusercontent.com/assets/22128752/18956944/f0da4a8e-8665-11e6-9c0e-db531bbc46a4.png)
![image](https://cloud.githubusercontent.com/assets/22128752/18956956/fb35a4ec-8665-11e6-8951-d15fcafe4d53.png)

**Comment by Strinkor** [comment]
Что это за хрень?

**Comment by silentenemy** [comment]
no no no *no no no* ***no-no-no-no*** **NO!!**

**Comment by Qwertyon666** [comment]
**¯\_(ツ)_/¯**

**Comment by silentenemy** [comment]
Мы проебали 2^8-гет на это говно.

**Comment by Euronem** [comment]
![image](https://cloud.githubusercontent.com/assets/17518355/18994206/6859dc40-872f-11e6-8d51-4c2133d00401.png)
