### ISSUE TITLE
Брут и берн патчи лечат урон у протезов

### ISSUE THREAD

**Issue by Mioru** [animusdev/green#263]
http://s41.radikal.ru/i091/1609/3e/24dc82dd9e7c.png
Вот у меня тут протезная левая рука. По логу видно, что несколько секунд назад у меня был брут урон по всему телу, в том числе и на этой самой роботизированной левой руке. Затем я применяю брут патч на **живую** часть тела. При этом исцеляется всё, в том числе и поврежденная протезная рука, которая, по идее, исцеляться от этого не должна.
Точно такая же история и с бёрн патчами и обожженными протезными частями тела. 
Не получится этим всем пользоваться только в том случае, если роботизированы вообще все части тела.

(Также один медик обнаружил баг с появлением двух рук при операции по протезированию.
Судя по всему, проявляется он, если сперва отрезать руку неоперационным методом, а затем провести на этой же руке операцию по протезированию.
Сперва он отрезал мне правую руку циркуляркой - без операции. Затем, как я понимаю, он принялся пошагово проводить соответсвующую операцию. В ходе её, на этапе отрезания, появилась вторая точно такая же правая рука.
Но конкретно эту штуку с дублированием рук желательно перепроверить.)

**Comment by silentenemy** [comment]
fucking augs!

**Comment by Euronem** [comment]
юра, блядь

**Comment by bo20202** [comment]
>Вот у меня тут протезная левая рука. По логу видно, что несколько секунд назад у меня был брут урон по всему телу, в том числе и на этой самой роботизированной левой руке. Затем я применяю брут патч на живую часть тела. При этом исцеляется всё, в том числе и поврежденная протезная рука, которая, по идее, исцеляться от этого не должна.
Это тгмедицина, тут так можно
