### ISSUE TITLE
Порция одежды

### ISSUE THREAD

**Issue by Qwertyon666** [animusdev/green#277]
Вот 
https://cdn.discordapp.com/attachments/232237863591215105/232591139041968129/black_hoodie.dmi
и вот
https://cdn.discordapp.com/attachments/232237863591215105/232573375036260352/women_hoodie.dmi
Сам пилить одежду я не могу, по-этому кидаю сюда

**Comment by fluorescent-net** [comment]
Resolved by https://github.com/animusdev/green/pull/276.

**Comment by ucnaHez** [comment]
Чо. Причем тут это?

В тот реквест я впилил давно схороненные спрайты тряпья, а тут вообще не то.

**Comment by Qwertyon666** [comment]
Ну дык что?

**Comment by Qwertyon666** [comment]
Хуйня криво нарисована
