### ISSUE TITLE
Ползаем под столом

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#283]
_грейтест-уннахез-айдиас_

Было несколько раз в мелких идеях.

ПОЛЗАНИЕ ПОД СТОЛОМ!

Например, перетаскиванием себя лежачего на стол. Встать ты не можешь, свободно кравлить под столами тоже - только перетаскиванием на соседние столы. С возможностью НАШУМЕТЬ. Возможно, предметы можно выкладывать под стол, хотя это жирно.

Зачем? Так ведь ГЛАВЫ ПРЯЧУТСЯ ПОД СТОЛОМ ОТ РЕВОВ!

discussion_needed

**Comment by silentenemy** [comment]
бля, вот это охуенно, вот это надо добавить

**Comment by DrDeath31** [comment]
лучше наверное просто добавить возможность ползать лежа. В одном из билдов есть такая фича. у кнопки Rest появится еще смысл жить!

**Comment by silentenemy** [comment]
СЕКРЕТНЫЕ РАЗРАБОТКИ ТАУ КИТА: К Р А В Л

**Comment by ucnaHez** [comment]
>у кнопки Rest появится еще смысл жить

Он появился с тех пор, как ее вернули шорткаты и на интерфейс.

**Comment by Qwertyon666** [comment]
У грудоломов есть кнопка hide. Может ее просто завязать на лежачее положение - лег и автоматом включается hide + ползание?

**Comment by ucnaHez** [comment]
Неее. все проще и без КРАВЛА, который впиливать надо комплексно.
