### ISSUE TITLE
Маняфича для OOC

### ISSUE THREAD

**Issue by Qwertyon666** [animusdev/green#297]
Предлагаю после бана игрока  в OOC выводить сообщение типа:
%c.key% has been eat by grue.
Ну или:
%c.key% принесен в жертву сингуло.
Можно вообще сделать несколько вариантов фраз, рандомно выбираемых системой.

**Comment by Euronem** [comment]
не

**Comment by ucnaHez** [comment]
Если педаль хочет похвастаться тем, что он забанил всеми нелюбимого дауна - он хвастается в ООС. А писать о каждом малогее - нафига?

**Comment by Qwertyon666** [comment]
А по-моему забавно :3

**Comment by Strinkor** [comment]
Не, не оче фича.
