### ISSUE TITLE
Поставить в середине станции памятник Харамбе

### ISSUE THREAD

**Issue by Truncated21** [animusdev/green#310]
Харамбе умер за наши грехи. Я считаю, что нужно поставить памятник в его честь. Или сделать живое воплощение Харамбе на станции.

**Comment by Euronem** [comment]
![image](https://cloud.githubusercontent.com/assets/17518355/19412550/88ee6004-9321-11e6-83b7-cd8ad89bf51a.png)
![image](https://cloud.githubusercontent.com/assets/17518355/19412550/88ee6004-9321-11e6-83b7-cd8ad89bf51a.png)
![image](https://cloud.githubusercontent.com/assets/17518355/19412550/88ee6004-9321-11e6-83b7-cd8ad89bf51a.png)

**Comment by Truncated21** [comment]
black lives matter

**Comment by Azero777** [comment]
Кто это вообще?

**Comment by ucnaHez** [comment]
О чем эти поехавшие?

**Comment by fluorescent-net** [comment]
-_-
