### ISSUE TITLE
Боевой огнемёт.

### ISSUE THREAD

**Issue by fluorescent-net** [animusdev/green#32]
Использует флогистон. Выглядит сурово. Даётся дедскваду, нюкерам, возможно, триторам за большую цену. Ярида обещал спрайты.

**Comment by Zooopppaaa** [comment]
Можно запилить реактивный огнемёт типо Шмеля или Флэша, который будет стрелять снаряд-ракетами с огнесмесью. Или сделать что-то типо плазменного огнемёта, который будет подключен к рюкзаку со смесью. Как-то так
