### ISSUE TITLE
Я не могу лечиться или помочь другим, когда врачи ушли/пропали/дураки/хуи/мертвы или их даже не завезли.

### ISSUE THREAD

**Issue by Seldorne** [animusdev/green#321]
1) Снять доступ с кнопки дверей в приёмной. Для жлобов есть ставни, которые не дадут добраться до этой кнопки.
2) Вынуть аптечки из заблокированного шкафчика и вернуть на столы. Восстановить их в количестве, т.е. снова по три аптечки каждого вида.

**Comment by Euronem** [comment]
![image](https://cloud.githubusercontent.com/assets/17518355/19598891/fc99f6ca-97a5-11e6-90e6-ab880b96c225.png)
Страдай.

**Comment by Seldorne** [comment]
@Euronem Не хочу, не могу, не буду!

**Comment by jammer312** [comment]
Надо интегрировать наностолы в вирусологию и генетику

**Comment by Strinkor** [comment]
Чо за наностолы? @jammer312

**Comment by ucnaHez** [comment]
>посоны, не надо мержить это говно, это глупая идея
>вмержили
>посоны, откатите это говно, это глупая идея

Development.

**Comment by jammer312** [comment]
@Strinkor Особые столы, частично из металла, частично из стекла, созданы с использованием передовых нанотехнологий, гармонично вписываются в интерьер.

У тебя правый стол в медхранилище на треть из металлического, на две трети из стеклянного состоит.

**Comment by ucnaHez** [comment]
А вообще - давайте инженерам запрем раздатчик с канистрами плазмы - хуле всякие ассистонты сингу настраивают, пока инжей нет? НИПОРЯДОК, РАБОТКУ ОТОБРАЛИ

И карту запасную выпилим, а то чо всякие ассистенты шаттл вызывают без глав.

**Comment by jammer312** [comment]
Дык канистра плазмы и так заперта, а без заправки плазмой у синги выход хиловат.

**Comment by Seldorne** [comment]
Нужно ещё решить с кнопкой у СЕ. Ведь кнопка у СЕ есть, и она не ограничена доступом. Это непорядок! Тоже надо доступ туда поставить. Причём желательно доступ СЕ. А то инженеры без СЕ в хранилище залезают. Да и любой ассистент залезает и ворует канистру с плазмой, и пускает её в коридор.

**Comment by jammer312** [comment]
Мхех. Для того, чтобы открыть хранилище, нужна только карта инженера и лом. И никаких кнопок.

**Comment by Seldorne** [comment]
@jammer312 Тсссс! Стринкор услышит.

**Comment by Strinkor** [comment]
@Seldorne Остроумная шутка. Пригорай дальше, что я могу сказать.

**Comment by fluorescent-net** [comment]
Бля, ну что ж вы за люди.
Это кнопки. Кнопки, не картридеры и не биометрические системы аутентификации. Обычные, блядь, кнопки. Мы с Роджером сколько ползали по карте и выпиливали доступы с каждой из них - а вы крякаете и невесть зачем закручиваете гайки, игнорируя критику и хотя бы тот факт, что с кнопками без доступа карта живёт уже добрый год - и нормально.

Либо делайте для действительно критичных мест новое устройство с отдельным спрайтом, либо не делайте бессмысленных изменений, которые только усугубляют общий аутизм.
