### ISSUE TITLE
Может пора?

### ISSUE THREAD

**Issue by kreeperHLC** [animusdev/green#328]
Я предлагаю взять всё самое лучшее что есть на новоТГ и добавить это на Грин. Конечно это займёт очень много времени, но зато Грин станет более новее и интереснее без нерфоцирка и прочего.

**Comment by silentenemy** [comment]
А поконкретнее можно?

**Comment by Euronem** [comment]
Окей.
Давай представим. Сейчас у грина один активный кодер. Это сайлент.
Давай представим разрыв межу билдами за полтора года. (ТГ-рин поставили в начале июня 15, есче.)
И давай подумаем, нужно ли ему это? Если хочешь - гайд по гиту есть в ридми, а копипастить код может даже больной ДЦП ребенок

**Comment by kreeperHLC** [comment]
@silentenemy Обновить ботанику (Новые семена, ДНК модификатор их), обновить РнД (Добавить новые предметы, которые можно будет изготовить, добавить новые импланты, добавить улучшения для боргов, новые консоли управления слаймами и их новые эффекты от экстрактов), обновить СБ (Новые орудия для убийства/задержания заключенных, автоматический телепорт для заключенных на астероид), добавить теслу, обновить Карго (Добавить новые ящики, систему аукционов и продажу всего и вся), добавить Лаваленд и новые рецепты.

**Comment by Qwertyon666** [comment]
Зачем нам тесла? Нам и с синьгой хорошо

**Comment by silentenemy** [comment]
>добавить теслу

Нахуй. Тесла для казуалов. Говно ебучее.

>добавить Лаваленд

Нахуй. Я дварфошахты не допилил, а вы мне предлагаете спиздить лаваленд.

>новые рецепты

_Веселые Крафты 3: Вам Молотов в Ебало?_

>обновить СБ

Мы работаем над этим. И да, у нас есть ПЕПС :^)

>обновить РнД
Сделай сам, плиз. Я даже не представляю, сколько говна придется портировать и сколько говна придется переделывать с тгхуев на нанохуи/штмл.

>Обновить ботанику
Джаммер занимался вроде бы этим.

**Comment by Truncated21** [comment]
![image](https://cloud.githubusercontent.com/assets/17429347/19742061/0ce679f2-9bcc-11e6-8663-b947a91cfa8d.png)

**Comment by kreeperHLC** [comment]
Так и знал, что делать этот иссуй это плохая идея
