### ISSUE TITLE
Многоуровневая синга!

### ISSUE THREAD

**Issue by Dark-Magov** [animusdev/green#339]
Собственно нынче синга висит только на одном уровне, шо не есть хорошо.

Пока предложенные при обсуждении варианты таковы:
- синга притягивает на других этажах, скачет когда вне полей
- Синга имеет меньшее отображение на других этажах, скачет по этажам, многоэтажные силовые поля (и инженерка)

**Comment by Strinkor** [comment]
Предлагаю вариант №2, он хоть и сложнее, но поинтереснее будет.

**Comment by Seldorne** [comment]
На Луне суперматерия была не просто так - сама никогда не ускачет.
