### ISSUE TITLE
Конусообразный свет фонариков.

### ISSUE THREAD

**Issue by fluorescent-net** [animusdev/green#34]
Понерфать фонарики, введя большой тактический простор - бэкстабы, нервное оглядывание назад в техах, вот это вот всё.

**Comment by OdSt** [comment]
Ну рак же. Вы еще FOV предложите для фуллхауса.

**Comment by fluorescent-net** [comment]
> Ну рак же. Вы еще FOV предложите для фуллхауса.

Ну FOV-то как раз и нахуй не нужен в ссочке, а это можно попробовать. Приживётся - оставим, не приживётся - выпилим к хуям.

**Comment by OdSt** [comment]
Так уже запиливали, ну хуево было, и выпилили.

**Comment by Core0verload** [comment]
Как минимум будет веселье оптимизации из-за того, что свет надо пересчитывать даже не при каждом шаге, а при каждом повороте. Плюс наверняка выглядеть будет криво.

**Comment by Plastmassa** [comment]
Проблема в том, что ИРЛ фонарик ещё можно крутить в руках и головой тоже можно крутить. Тут уже получается жёсткое закрепление за направлением персонажа.

**Comment by OdSt** [comment]
Лучше бы пофиксили фонарики в шкафах. А то они как в 2012 оставляли свет, так и сейчас.

**Comment by fluorescent-net** [comment]
> Лучше бы пофиксили фонарики в шкафах. А то они как в 2012 оставляли свет, так и сейчас.

Ну, ёпта, можно было и тикет написать, если ты проблему видел, а мы не в упор не замечали.

**Comment by OdSt** [comment]
Не, это мне лень. Короче, закро

**Comment by OdSt** [comment]
Не, это мне лень. Короче, закрой фонарик в шкафу и подвигай. Там будет понятно в чем беда.
