### ISSUE TITLE
Портировать ксеноархеологию с Бэя

### ISSUE THREAD

**Issue by bo20202** [animusdev/green#35]
В условиях грифозности космонавтиков артефактами можно будет творить  небывалый !!!FUN!!!

**Comment by OdSt** [comment]
Нет-нет и еще раз нет. В нее и так аутировало 3,5 космонавтика в лучшие времена. Крайне сомнительно с точки зрения фана. Так еще и аутистов привлечете.

**Comment by fluorescent-net** [comment]
действительно сомнительно в отличии от метроидов
