### ISSUE TITLE
Если глянуть в Хаб, мы можем обнаружить, что слишком много у нас рантаймов.

### ISSUE THREAD

**Issue by Strinkor** [animusdev/green#355]
> runtime error: Cannot read null.state
> proc name: update hair (/mob/living/carbon/human/update_hair)
> source file: update_icons.dm,138
> usr: (src)
> src: Ethan Palmer (/mob/living/carbon/human)
> src.loc: the floor (111,82,1) (/turf/simulated/floor/plasteel)
> call stack:
> Ethan Palmer (/mob/living/carbon/human): update hair()
> Ethan Palmer (/mob/living/carbon/human): update inv wear suit(0)
> Ethan Palmer (/mob/living/carbon/human): equip to slot(the labcoat (/obj/item/clothing/suit/toggle/labcoat), 13, 0)
> Ethan Palmer (/mob/living/carbon/human): equip to slot if possible(the labcoat (/obj/item/clothing/suit/toggle/labcoat), 13, 0, 0, 0)
> Ethan Palmer (/mob/living/carbon/human): attack ui(13)
> the o_clothing (/obj/screen/inventory): Click(null, "mapwindow.map", "icon-x=9;icon-y=16;left=1;scre...")
> runtime error: Cannot read null.state
> proc name: update hair (/mob/living/carbon/human/update_hair)
> source file: update_icons.dm,138
> usr: (src)
> src: Ethan Palmer (/mob/living/carbon/human)
> src.loc: the floor (126,143,1) (/turf/simulated/floor/plasteel)
> call stack:
> Ethan Palmer (/mob/living/carbon/human): update hair()
> Ethan Palmer (/mob/living/carbon/human): update inv wear suit(0)
> Ethan Palmer (/mob/living/carbon/human): unEquip(the labcoat (/obj/item/clothing/suit/toggle/labcoat))
> the labcoat (/obj/item/clothing/suit/toggle/labcoat): MouseDrop(the r_hand (/obj/screen/inventory), null, null, "mapwindow.map", "mapwindow.map", "icon-x=19;icon-y=12;left=1;scr...")
> runtime error: Cannot read null.state
> proc name: update hair (/mob/living/carbon/human/update_hair)
> source file: update_icons.dm,138
> usr: (src)
> src: Ethan Palmer (/mob/living/carbon/human)
> src.loc: the floor (135,163,1) (/turf/simulated/floor/plasteel)
> call stack:
> Ethan Palmer (/mob/living/carbon/human): update hair()
> the mirror (/obj/structure/mirror): attack hand(Ethan Palmer (/mob/living/carbon/human))
> Ethan Palmer (/mob/living/carbon/human): UnarmedAttack(the mirror (/obj/structure/mirror), 1)
> Ethan Palmer (/mob/living/carbon/human): ClickOn(the mirror (/obj/structure/mirror), "icon-x=17;icon-y=18;left=1;scr...")
> the mirror (/obj/structure/mirror): Click(the floor (135,163,1) (/turf/simulated/floor/plasteel), "mapwindow.map", "icon-x=17;icon-y=18;left=1;scr...")
> Wed Nov 2 17:56:11 2016
> runtime error: Cannot read null.state
> proc name: update hair (/mob/living/carbon/human/update_hair)
> source file: update_icons.dm,138
> usr: null
> src: Ethan Palmer (/mob/living/carbon/human)
> src.loc: the floor (105,56,1) (/turf/simulated/shuttle/floor)
> call stack:
> Ethan Palmer (/mob/living/carbon/human): update hair()
> Ethan Palmer (/mob/living/carbon/human): ChangeToHusk()
> Ethan Palmer (/mob/living/carbon/human): updatehealth()
> Human (/datum/species/human): handle chemicals in body(Ethan Palmer (/mob/living/carbon/human))
> Ethan Palmer (/mob/living/carbon/human): handle chemicals in body()
> Ethan Palmer (/mob/living/carbon/human): Life(2)
> Ethan Palmer (/mob/living/carbon/human): Life(2)
> Ethan Palmer (/mob/living/carbon/human): Life(2)
> Mobs (/datum/subsystem/mobs): fire(0)
> /datum/controller/game_control... (/datum/controller/game_controller): process()
> runtime error: Cannot read null.status
> proc name: handle body (/datum/species/proc/handle_body)
> source file: species.dm,197
> usr: null
> src: Human (/datum/species/human)
> call stack:
> Human (/datum/species/human): handle body(Ethan Palmer (/mob/living/carbon/human))
> Ethan Palmer (/mob/living/carbon/human): update body()
> Ethan Palmer (/mob/living/carbon/human): ChangeToHusk()
> Ethan Palmer (/mob/living/carbon/human): updatehealth()
> Human (/datum/species/human): handle chemicals in body(Ethan Palmer (/mob/living/carbon/human))
> Ethan Palmer (/mob/living/carbon/human): handle chemicals in body()
> Ethan Palmer (/mob/living/carbon/human): Life(2)
> Ethan Palmer (/mob/living/carbon/human): Life(2)

**Comment by Dark-Magov** [comment]
Я бы не бел так уверен шо это именно юра, это может ещё и сайлент.

**Comment by silentenemy** [comment]
а я-то что, я только ксеносов трогал, а ксеносов я там не вижу

**Comment by bo20202** [comment]
у меня всё работало, я не виноват

**Comment by Dark-Magov** [comment]
У Стринкора тоже всё работало пока ему не сказали шо речь вообще о другом, а не о том, о чём он подумал.
