### ISSUE TITLE
Проблемы с лозой

### ISSUE THREAD

**Issue by jammer312** [animusdev/green#358]
- [x]  Кислотные лозы не устойчивы к plant-b-gone (хотя должны быть).

- [ ] Конфликты мутаций не работают.

- [ ]  Не работает заражение гуманоидов пчеловирусом(срабатывает, но не заражает).

- [x]  Творится какая-то лажа с флагами. Т.е. быстрая лоза после мутации света уже не быстрая лоза(быстрая мутация есть, но не работает), стеклянная лоза после мутаций не ломается тупыми предметами и тому подобное.

**Comment by Dark-Magov** [comment]
Добавил тасклист.
