### ISSUE TITLE
Трубы Вирусологии

### ISSUE THREAD

**Issue by Vadkop** [animusdev/green#360]
https://puu.sh/s87oz.jpg
Вот на скрине видно, что одна из аир алярм мигает красным. Так же видно, что канистра подключена к коннектору. Но в комнате с мигающей алярмой нет ни венты, ни скрабера. Зато у мартышек, где нет аир алярма, есть и венты, и скрабер. 
Блять, охуенный скрин, на нем алярма как раз мигнула и она теперь темная. Я вот про эту комнату, короче: https://puu.sh/s87EQ.jpg

**Comment by Strinkor** [comment]
#53ddf7f
