### ISSUE TITLE
Тайлобаги

### ISSUE THREAD

**Issue by Vadkop** [animusdev/green#364]
Если тайл опенспейса покрыть плиткой, то там появляется вот такой черный тайл: https://puu.sh/scpOv.jpg 
Баг появляется только с металлической плиткой, если покрыть деревянным полом, то все нормально.
Починить можно постройкой стены и ее разборкой.

**Comment by Dark-Magov** [comment]
Тайлпейнтером покрась.

**Comment by Seldorne** [comment]
А у тайлпейнтера нет половины спрайтов.
