### ISSUE TITLE
Хронопушки и глаз ИИ

### ISSUE THREAD

**Issue by Dark-Magov** [animusdev/green#37]
Если попасть хронопушкой  в ИИ, в хороносверу попадает глаз ИИ.
В итоге **оно пытается удалить глаз ИИ и роняет сервер**.

Эти хронопушки выпилить надо.

**Comment by silentenemy** [comment]
Надо пофиксить, а не выпиливать.

**Comment by Plastmassa** [comment]
Тебя выпилить надо, ты тоже роняешь игры.

**Comment by DeeperCoder** [comment]
Лучше, конечно, оставить. А баг профиксить.
