### ISSUE TITLE
Синьгу сломали!

### ISSUE THREAD

**Issue by Qwertyon666** [animusdev/green#376]
![image](https://cloud.githubusercontent.com/assets/22128752/20361678/86fc030a-ac49-11e6-9278-cce963cf1277.png)
![image](https://cloud.githubusercontent.com/assets/22128752/20361680/8a13de14-ac49-11e6-9cfb-f0326b69e0f4.png)

**Comment by Vadkop** [comment]
Она просто ВНИЗУ.

**Comment by Qwertyon666** [comment]
Во-первых, она была одна
Во-вторых, хули она не сосет?

**Comment by jammer312** [comment]
Cказали же, она ВНИЗУ

**Comment by Qwertyon666** [comment]
Так в том от и проблема, где теперь урон станции?
Его нет(

**Comment by fluorescent-net** [comment]
ХАХАХАХААХХХА ХАХАХА ХХХААХАХАА!!!!!!!!!

**Comment by jammer312** [comment]
#339

**Comment by Qwertyon666** [comment]
https://cdn.discordapp.com/attachments/154659905234534400/264943666332696596/unknown.png
┬─┬﻿ ノ( ゜-゜ノ)

**Comment by Dark-Magov** [comment]
Тебе в 3 раз сказаь что синга просто внизу а мильтиэтажную пока не завезли?

**Comment by ucnaHez** [comment]
/close

Многоэтажная синга завезена.
