### ISSUE TITLE
Шахтеры-зеки и доступы

### ISSUE THREAD

**Issue by Vadkop** [animusdev/green#380]
![Дверка!](https://puu.sh/sukI5.jpg)
Вот у этой двери нет доступа на шахтерке брига.

**Comment by Srankl1n** [comment]
Шлюз, сука, а не дверь

**Comment by Vadkop** [comment]
Дверь.

**Comment by Strinkor** [comment]
Сук, сделайте БОЛЬШОЙ ИССУЙ по поводу карты, заебали.
