### ISSUE TITLE
Metroid

### ISSUE THREAD

**Issue by Seldorne** [animusdev/green#381]
Как вы воспринимаете идею о замене слизней обратно на метроидов? 
Реакций там немного, конечно, и они не слишком интересные, но вопрос, скорее, не в них, а просто в замене приевшихся слаймов на что-то новое (старое).

**Comment by TheOneForgotten** [comment]
Многовато менять. Не стоит того.

**Comment by TeaChaser** [comment]
Не менять, а добавить! Ну, левая сторона будет для слаймов, правая для метроидов. Ибо слаймы тоже пиздаты тем, что ими можно командовать

**Comment by Euronem** [comment]
кряяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяяя

**Comment by silentenemy** [comment]
#36

**Comment by bo20202** [comment]
я пытался это сделать, но понял что оно того не стоит. Хотя бы из-за того, что мало реакций. Другое дело, тупо заменить спрайты, а ядра оставить слизневские, вот над этим уже можно покумекать.

**Comment by silentenemy** [comment]
Лучше #76 впилить. Ксенобио в сотрудничестве с гидропоникой представляет вам АГРЕССИВНЫХ КОСМОРОСЯНОК

**Comment by Seldorne** [comment]
@Euronem Кря! ^_^

А ещё косморосянки.
А ещё матки пауков из горшочков, а не только охотники.
А ещё какая-нибудь ксеноботаника (хз, что это)
...
Одни слаймы скучные.

**Comment by Seldorne** [comment]
@bo20202 Почему-то у белых слаймов выпилена замечательная возможность телепортации - только спавн кристалла остался.

**Comment by jammer312** [comment]
Выпилена потому, что телепортировать одной гранатой всех из шаттла в космос - не самая балансная фича

**Comment by jammer312** [comment]
А #76 очень лозу напоминает, точнее, из лозы такую росянку можно собрать (разве что хватать и поливать будет не отдельные части тела, а всего космонавта сразу)

**Comment by Seldorne** [comment]
В общем, никого это не радует, и не то чтобы даже интересно. Жаль.
