### ISSUE TITLE
Выпало нон-рп имя. 

### ISSUE THREAD

**Issue by Lyaskavka** [animusdev/green#382]
Grandpa Christopher. 
Grandpa переводится как дедушка. Написал Dark_magov сменить имя, я понимаю причину, но объяснился тем,что выпало само. 
Может в коде  есть еще "слова" в списке имен? Или это фича?

**Comment by jammer312** [comment]
Имен там 725 для мужчин, 806 для женщин, еще фамилий 620.
Уверен ли ты в том, что *стоит* проверять их все на соответствие российскому пониманию имени/фамилии?

**Comment by Lyaskavka** [comment]
Мне админ написал,чтоб я имя сменил. Ну, если не баг, так не баг.
