### ISSUE TITLE
LOOC - Надо или нет.

### ISSUE THREAD

**Issue by Strinkor** [animusdev/green#388]
Ну суть ясна из заголовка.

**Comment by Ein-Linet** [comment]
Nope.

**Comment by Qwertyon666** [comment]
А что это? :3

**Comment by Lyaskavka** [comment]
Надо, и я не понимаю людей, которые гвоорят, что нет
я что, должен тому же капитану на весь чат объяснять как использовать консоль или если роль маломальский, чтоб спалить режим?

**Comment by Euronem** [comment]
Nope

**Comment by fluorescent-net** [comment]
Раньше был радикально против, теперь не вижу ничего плохого.

**Comment by Lyaskavka** [comment]
А почему нет, опять таки? Объясняя что-то новичку в ООЦ можно что-то спалить. Спалить его профу, его роль, чем он занимается. Это надо? Нет. Это все равно что комментировать раунд

**Comment by ucnaHez** [comment]
Не.

Все полторы полезности нивелируются отрицательным использованием всяческими мудаками.

Говори в ООС, или проси педалю передать, благо одна или две на грине висят всегда-всегда.

**Comment by Lyaskavka** [comment]
Во первых, зачем каждый раз без повода или с поводом дергать педаль?
Во вторых, а что если культ? Я в ООЦ должен обхяснять человеку как пользоваться книжкой? В ЛООЦ меньше шансов спалить режим на весь сервер.

**Comment by ChristianAnderssen** [comment]
Настоящий космонавт объяснит как пользоваться книжкой ингейм.
