### ISSUE TITLE
Вскрытие как причина смерти.

### ISSUE THREAD

**Issue by Strinkor** [animusdev/green#389]
https://wiki.baystation12.net/Guide_to_Cadavers
Вернуть вот эту хуету, я еще года 2.5 назад с ней баловался и было весело, дискасс.

**Comment by Shluher** [comment]
у вас блядь тг, причину смерти можно интуитивно понять через анализатор медицинский

**Comment by Strinkor** [comment]
@Shluher Тогда будем веселиться со вскрытием, чо тут.

**Comment by NazarFogmann** [comment]
Спиздить и перепилить с парадайза как вариант
