### ISSUE TITLE
Meme (for me)

### ISSUE THREAD

**Issue by Qwertyon666** [animusdev/green#390]
Баги, глюки, и прочая лабуда, которая касается Мемо:
 - [x] 1) У мемо нет имени.
 - [x] 2) Мемо нет в списке антагов.
 - [x] 3) Мемо исчезают из плеер панельки.
 - [x] 4) Вне зависимости от кол-ва хостов, может быть только один мемо, так как все предложки кидает только одному рандомному госту.
  - [x] 5) У Мемо нет цели.
- [x] 6) Если генка примет малую форму, то Мемо умрет.
 - [x] 7) Когда Мемо говорит, не появляется облачко.
 - [x] 8) Если заткнуть хозяина, то Мемо не сможет говорить, а должен.
 - [x] 9) После смерти хозяина Мемо выкидывает. Нахуй. Из Игры. Перезаход кидает в лобби.
 - [x] 10) Мемо не умирает, если хост без сознания.

**Comment by Strinkor** [comment]
Норм так вкатили. 
зы: я криворукий.

**Comment by Qwertyon666** [comment]
В плане чего?
