### ISSUE TITLE
Внеси ёлку

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#405]
Новый год на носу, где музычка в лобби и джукбоксе? Где хлопушки? Где гирлянды по всей станции? Где, наконец, ЁЛКА?

Люто реквестирую.

**Comment by Invaser777** [comment]
Музыку в жукбоксе и не убирали с прошлого года (прям как ёлку).

**Comment by Dark-Magov** [comment]
Можем поставить ещё одну ёлку на ту которая уже есть.

**Comment by Invaser777** [comment]
А вообще да, кроме елки и музыки в баре не чувствуется новогоднего настроения, гирлянд бы и всяких новогодних штучек, которые валяются по станции.

**Comment by ucnaHez** [comment]
>елка в баре
>елка в баре
>елка в баре

Я зашел на сервер, оббежал весь бар, открыл файл мапы, обсмотрел его всего

НЕТУ НИКАКОЙ ЕЛКИ

**Comment by Dark-Magov** [comment]
Нормальные маперы ставят ёлки к новому году.

@Strinkor Заменяет их на сакуру.

**Comment by Invaser777** [comment]
![sprite-0001](https://cloud.githubusercontent.com/assets/17705943/21295778/1e9c880e-c565-11e6-825b-6304bada171c.png)
)

**Comment by Strinkor** [comment]
@Dark-Magov Поставим мы вам елку.
