### ISSUE TITLE
Соляная комната и медбей

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#407]
На входу в медбей и в соляной комнате кнопки с ПРОВЕРКОЙ ДОСТУПА.

Что это за ересь? Вы расстраиваете роджи, выпилите это говно.

**Comment by Dark-Magov** [comment]
Это всё происки лольца

**Comment by Strinkor** [comment]
@ucnaHez ТЫ всегда можешь зайти с техов, где вход не табуирован.

**Comment by ucnaHez** [comment]
Шо? Где-то в медбее есть теха с дверью без доступа? В первый раз слышу.

**Comment by Strinkor** [comment]
В комнату, где вход в соляную комнату через техи может любой зайти.

**Comment by ucnaHez** [comment]
Не, я о том, что КНОПКА в самой соляной комнате, открывающая окошечки, под доступом. Как и кнопка на входе в мед.
