### ISSUE TITLE
Неправильное отображение персонажа, снимающего одежду

### ISSUE THREAD

**Issue by silentenemy** [animusdev/green#41]
![ss 2016-02-21 at 06 31 14](https://cloud.githubusercontent.com/assets/5739068/13203454/1a4eb7de-d8d2-11e5-8d55-7e2488126b3b.png)
Человек, если с него снимает одежду некоторый персонаж, видит в сообщении You, но не имя этого персонажа.

**Comment by fluorescent-net** [comment]
https://github.com/animusdev/green/pull/42/
