### ISSUE TITLE
Взрывы и z-уровни

### ISSUE THREAD

**Issue by fluorescent-net** [animusdev/green#421]
- [ ] Взрыв, уничтожающий пол на верхнем уровне, сбрасывает крупные объекты (машинерию), трубы и различные функциональные элементы (пожарные сингализации, кнопки) на уровень ниже. Трубы, пожалуй, нужно уничтожать, а вот настенные элементы либо как-то хендлить, либо переносить по всей карте на стены.
- [ ] Реализовать воздействие взрывов на верхние от эпицентра z-уровни.

**Comment by Dark-Magov** [comment]
>а вот настенные элементы либо как-то хендлить, либо переносить по всей карте на стены.

Хендлить без проблем, только нужен список всех настенных предметов.

**Comment by ucnaHez** [comment]
А еще интеркомы.

Они вообще не прикреплены к стенам, каждый мало-мальский взрыв откидывает их аки листья во все стороны.
