### ISSUE TITLE
Бля, консоль упала, хуй шаттл вызовешь

### ISSUE THREAD

**Issue by Srankl1n** [animusdev/green#436]
Если консоль коммуникаций КАКИМ НИБУДЬ ХУЕМ упадёт в подвал то шаттл нельзя вызвать с ризоном "СЛИШКОМ ДАЛЕКО ОТ СТАНЦИИ"

**Comment by silentenemy** [comment]
Так подними её, хуле тебе непонятно?
*надо запилить домкрат*

**Comment by ucnaHez** [comment]
Действительно, нашел проблему. Развинтил там, свинтил тут.

А оно не должно автовызываться из-за отсутствия консолей на уровне станции?

>надо запилить домкрат

тема. Возможность таки разбирать пол без бомб, и лебедку на колесиках. Разбираешь пол, подтаскиваешь ее к опенспейсу, жмешь, она автоматом поднимает то, что внизу, сюда.

**Comment by Seldorne** [comment]
Это не баг. Можно вызывать только с консолей на первом уровне, а подвал - это не первый уровень.

**Comment by ucnaHez** [comment]
/totally_not_a_bug

Не вижу бага, упала - развинти

**Comment by Strinkor** [comment]
Удвою оратора выше, не баг. Хочешь шаттл - пересобери наверху.
