### ISSUE TITLE
Геннадий ослеп

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#443]
Если геннадию выдать глазной урон - он его никак не снимет. Ни флешменд, ни панацея, ни трансформация не спасают.

**Comment by NazarFogmann** [comment]
окулин?
Крио?

**Comment by ChristianAnderssen** [comment]
>окулин?
Крио?

Умеешь воскресать, заживлять раны, отращивать конечности.
@ 
Не можешь вылечить слепоту. 

Было бы логичнее, если бы генокрад мог лечить глаза.
