### ISSUE TITLE
Б У М А Ж К А

### ISSUE THREAD

**Issue by Qwertyon666** [animusdev/green#474]
Вы так и не добавили **б у м а ж к у** на консоль ускорителя, а ведь даже они не видят этой лестницы. Кол-во проебанных син**ь**г уже начинает вызывать сомнения, не багнута ли она, а игроки просто не знают про второй уровень.

**(╯°□°）╯︵ ┻━┻**

UPD
Еще бы в смесы больше энергии изначально заправить или добавить заметку в **б у м а ж к у**, чтоб настраивали сразу соляры и энергии хватило наверняка.
Ах да, камер внизу тоже не хватает.

**Comment by ucnaHez** [comment]
зачем соляры?

Энергии хватает на всю огромную мету на полчаса, ее хватит еще на десять полей.

**Comment by Qwertyon666** [comment]
Допустим, но поставьте вы эту б у м а ж к у наконец
