### ISSUE TITLE
Шаттлопорты приделать

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/green#475]
Их сдувает сингой. И когда с обычным шаттлом это плохо и неудобно - он прилетает куда-нибудь в другое место - с подами это критично, потому что порт сдувает, а стенки остаются на месте, и не видно, куда садиться.

**Comment by Strinkor** [comment]
Ты хочешь сказать, что вот тот лэндмарк порта (который видно только на карте) ЗАСАСЫВАЕТ в сингу?

**Comment by ucnaHez** [comment]
Это не лендмарк, это натуральный обжект. Его нельзя таскать - у него invisibility, но срывать с болтов синга его вроде могла.
