### ISSUE TITLE
Подтверждение спавна спецролями.

### ISSUE THREAD

**Issue by fluorescent-net** [animusdev/green#62]
Когда на карте появляется лярва - госта автоматически туда пихает, нужен диалог с вопросом, хочет ли того игрок.
Так же касается ниндзей, блобов, абдукторов.

**Comment by OdSt** [comment]
Да, и с таймером. Что через 30 секунд автонет. По понятным причинам.

**Comment by fluorescent-net** [comment]
a60b26c69ded4d912c91f2acf208ad328a0b9741
