### ISSUE TITLE
Баги, баги

### ISSUE THREAD

**Issue by Invaser777** [animusdev/green#68]
Вкрации, есть 2 бага. Первый, это карты. Я захотел поиграть в карты, но не тут то было. Когда у меня в руке есть карты, я хотел выбросить одну из них. Открывается список, я нажимаю на нужную карту и...ничего. Пробовал нажимать на другие карты, но ничего не происходило. Второй баг- мулботы. Указываю я им место назначения, а они Unable reach location, или как-то так. Перепробовал всё, но впустую.
Передаю привет @MyLittleLoly

**Comment by fluorescent-net** [comment]
Всё вполне корректно берётся из руки. Видать, у тебя проблема с nanoui, попробуй почистить кэш.
Касаемо мулбота - точно так же не могу воспроизвести, он работает. Возможно, маячки были сломаны или что-то еще.
