### ISSUE TITLE
Бытовой телекинез

### ISSUE THREAD

**Issue by TheVarg** [animusdev/green#70]
Гринцы. Открыл аптечку в медбэе, убегая не закрыл её менюшку (содержимое).Через пять минут на другом конце карты достал себе в руку из той самой аптечки бинт и аналайзер.

**Comment by OdSt** [comment]
Надо бы повторить баг.

**Comment by fluorescent-net** [comment]
Тоже не могу воспроизвести.

**Comment by TheVarg** [comment]
Получилось с пончиками.

**Comment by OdSt** [comment]
Ну значит как-нибудь покажи нам, как это у тебя получилось, просто интересно, поскольку я так и не смог его воспроизвести.
