### ISSUE TITLE
Куча мелких косячков

### ISSUE THREAD

**Issue by Aidff** [animusdev/green#73]
- [ ] 1. Если поджечь листочек, листочек падает на пол и через время превращается в пепел без анимации горения.
- [x] 2. Любые жидкости в пипетке одинакового цвета (на вайтеке например кровь в пипетка красная, а плазма фиолетовая).
- [ ] 3. Отсутствие бюспейсрпеда и парочки уровней исследования не баг а фича?
- [ ] 4. Плавильня просто кусок мусора с ИГНАЙТЕРОМ И матер бином. 
- [x] 5. Адвансед плазма каттер занерфан в такое гавно, что им пользуются только дауны аутисты. (А ведь так то дохуя в ресурсах и уровнях стоит)
- [ ] 6. Эфедрин не работает. Нет ну он в стимпаке шахтеровском есть и вроде как УСКОРЯЕТ КОСМОНАВТИКА В КОСМОСЕ И В РИГЕ! Но почему-то без рига не хочет ускорять. ЭФЕДРИН КАКИМ ТО ОБРАЗОМ ОПРЕДЕЛЯЕТ ЕСТЬ ЛИ НА ЧЕЛОВЕКЕ РИГ ИЛИ НЕТУ? Если возможно запилите стандартное тгшное ускорение от эфедрина смешанного с сахаром иначе нет никакого смысла в этих стимпаках.
- [x] 7. Суперматерия двигается от потоков воздуха, она вроде как не настолько легкая, не?
- [ ] 8. Когда верезер ломает карго поинты на inf шаттл перестает прилетать. Очень обидно.
- [ ] 9. Отсутствует тгшная система кнута и пряника для карго (в листах назначения допускаются ошибки (иногда) и если такие ошибки отметить штампом денай засчитывает +50 очков или -25 если не заметил (отсылка к Papers, please)
- [ ] 10. В ящике с контрабандой нулевой шанс на хорошую контрабанду. (В итоге смысла от него еще меньше чем от ящика с шапками (хоть бы сюрикены засунули))
- [x] 11. В сигарете и сигаре одинаковый объем жидкости (по 15) на тгбилде (15 и 60)
- [ ] 12. Какая-то херня с объемом жидкостей в яйцах и с ее выплескиванием (всякие кислоты хорошо проходят, а вот зарядить туда вирусы и кидать их в ебало не получится (не заражают)
- [ ] 13. Было бы чудесно если на митспайк можно было наручники или провода вешать и человека не дамажило при подвешивании. (Выставить парочку неудачников перед бригом было бы пиздато)
- [x] ~~14. Слетели подписи у картин у мостика (раньше же вроде имена были под каждым, не?)~~
- [x] 15. Всего два генератора щитов (которые тайлы космоса закрывают) в инженерке. Ну два я поставлю у синги, а если я хочу дыру в отбытии заделать по быстрому? Добавьте еще два.
- [x] 16. Хим диспенсеры в химии НЕ ДВИГАЮТСЯ. Они одно целое с космосом и станцией? 
- [ ] 17. Моунтед флеш нельзя выковырять отверткой и ломиком.
- [ ] 18. Гену в сангласесах и с включенным термовизором все равно слепит флэш и вызывает у него повреждение глаз. Окулин его почему-то не лечит, а только операция.

**Comment by fluorescent-net** [comment]
>Суперматерия 

Ничего не перепутал? У нас материи отродясь не было.
По остальному пройдемся.

**Comment by bo20202** [comment]
> 1. Если поджечь листочек, листочек падает на пол и через время превращается в пепел без анимации горения.
Пофикшу, суть в том, что анимация горения появляется только от огня природного, не зажигалки.
> 11. В сигарете и сигаре одинаковый объем жидкости (по 15) на тгбилде (15 и 60)
Тоже пофикшу
>13. Было бы чудесно если на митспайк можно было наручники или провода вешать и человека не дамажило при подвешивании. (Выставить парочку неудачников перед бригом было бы пиздато)
Спрайтики бы

**Comment by Aidff** [comment]
И почему же тогда нельзя от эфедрина просто бегать быстрее? На тгбилде бегаешь как в жопу ужаленный генокрад но кончается эффект быстро. Суперматерию я заказывал и создавал движок вручную но от давления его кидало туда сюда.

**Comment by Dark-Magov** [comment]
> Ничего не перепутал? У нас материи отродясь не было.
Осколок суперматерии же, в карго заказывается,

> Суперматерию я заказывал и создавал движок вручную но от давления его кидало туда сюда.
Прикручивать к полу пробовал?

> Спрайтики бы
Так задай песелю, пока у того время есть. Ему как-раз делать нечего.

> а вот зарядить туда вирусы и кидать их в ебало не получится (не заражают)
Если там заражение по крови, оно и не должно.

>  Отсутствие бюспейсрпеда и парочки уровней исследования не баг а фича?
Таки не баг а простая разность версий, хотя спиздить всё-время собираются.

> Всего два генератора щитов (которые тайлы космоса закрывают) в инженерке. Ну два я поставлю у синги, а если я хочу дыру в отбытии заделать по быстрому? Добавьте еще два
Они вроде от синги не помогали, зачем они там?

**Comment by Aidff** [comment]
Прикручивать? Материю? Чтобы гибнуло нахуй? С кровью все окей было.Генераторы помогают от метеоритов и прочей мерзости.

**Comment by fluorescent-net** [comment]
https://github.com/animusdev/green/commit/781c93c74bb574c614556ac6c4f1fdd0dfce67f7
Прошёлся по части пунктов.

**Comment by Dark-Magov** [comment]
> Прикручивать? Материю? Чтобы гибнуло нахуй?

Код тонко намекает что ты не знаешь как это работает.

`/obj/machinery/power/supermatter_shard/attackby(obj/item/W as obj, mob/living/user as mob, params)`

	if(!istype(W) || (W.flags & ABSTRACT) || !istype(user))
		return
	if(istype(W, /obj/item/weapon/wrench))
		anchored = !anchored
		playsound(src.loc, 'sound/items/Ratchet.ogg', 75)
		return

**Comment by Aidff** [comment]
Хим диспенсеры все еще нельзя спиздить из химии. Это как-то не честно. На любом другом тгбилде можно.

**Comment by fluorescent-net** [comment]
Потому что мы еще не обновлялись, привет.

**Comment by Aidff** [comment]
ПРИВЕТ! КАК ДЕЛА?

**Comment by fluorescent-net** [comment]
Нормально. Обновимся - приходите с новыми жалобами.

**Comment by Euronem** [comment]
генераторы можно заказать в карго

**Comment by Aidff** [comment]
Конкретно ЭТИ нельзя

**Comment by Aidff** [comment]
ЗАПУСКАЕМ 
░ГУСЯ░▄▀▀▀▄░РАБОТЯГИ░░ 
▄███▀░◐░░░▌░░░░░░░ 
░░░░▌░░░░░▐░░░░░░░ 
░░░░▐░░░░░▐░░░░░░░ 
░░░░▌░░░░░▐▄▄░░░░░ 
░░░░▌░░░░▄▀▒▒▀▀▀▀▄ 
░░░▐░░░░▐▒▒▒▒▒▒▒▒▀▀▄ 
░░░▐░░░░▐▄▒▒▒▒▒▒▒▒▒▒▀▄ 
░░░░▀▄░░░░▀▄▒▒▒▒▒▒▒▒▒▒▀▄ 
░░░░░░▀▄▄▄▄▄█▄▄▄▄▄▄▄▄▄▄▄▀▄ 
░░░░░░░░░░░▌▌░▌▌░░░░░ 
░░░░░░░░░░░▌▌░▌▌░░░░░ 
░░░░░░░░░▄▄▌▌▄▌▌░░░░░

**Comment by Euronem** [comment]
6, 8, 9, 10 - не, с яйцами посмотрю, 3 - запиленно
С митспайками - тащи спрайты. 
Последнее - тоже не баг, а фича.

**Comment by Aidff** [comment]
Ну ты и ленивая жопа. Даже скопипастить с вайта не можешь.
