### ISSUE TITLE
Варден и проблемы с доступом

### ISSUE THREAD

**Issue by silentenemy** [animusdev/green#74]
У вардена нет доступа к Evidence Storage.

**Comment by Aidff** [comment]
А я в этом евиденс сторейдж вчера нашел БОЕВОЙ ДРОБОВИЧОК! Это нормально вообще?

**Comment by fluorescent-net** [comment]
Ну спавниться он там точно не должен, там спавнеры только майнтенс лута и катана.

**Comment by silentenemy** [comment]
Лично сегодня нашел дробовик.

**Comment by DeeperCoder** [comment]
Только что проверил - доступ у вардена есть.
