### ISSUE TITLE
Баги интерфейса

### ISSUE THREAD

**Issue by Seldorne** [animusdev/green#78]
Могут исчезать кнопки для масок, скафандров, фонариков и прочего подобного по одной за раз методом исчезания иконки у кнопочки. В пределах минуты-двух восстанавливаются, если сбросить/убрать вещь и снова взять/надеть.

**Comment by Dark-Magov** [comment]
Добавь скриншоты крана с пропавшими кнопками и попробуй найти/описать ситуацию которая приводит к пропаже.
