### ISSUE TITLE
Столы.

### ISSUE THREAD

**Issue by fluorescent-net** [animusdev/green#8]
- [x] сделать возможность _бегать_ по столам;

**Comment by john9911** [comment]
>сделать адекватную сборку/разборку (как на нт);
Это чтобы сразу table parts вываливались после разборки, а не разбор на лист металла и палочки?

**Comment by fluorescent-net** [comment]
@john9911
Именно.

**Comment by john9911** [comment]
У нас еще ковровые (ну для покера типа) и вообще рисовать придется же некоторые основы.
Проще сделать разбор ножек на лист металла, а не на две палки.

**Comment by fluorescent-net** [comment]
@john9911 А ковровые создаются за счёт добавления травы к деревянной основе. И спрайты всего этого были на нт. Ножки вообще не нужны.

**Comment by john9911** [comment]
Лишь бы выпилить! Разборы этих основ еще, чтобы с деревянного и кусок дерева выпадал, и металл. Хотя с ножками материалы справедливее распадались бы.

**Comment by fluorescent-net** [comment]
Ладно, согласен, система вменяемая.

**Comment by OdSt** [comment]
Кек. Ну вы издеваетесь. Убогая система с рамками для столов не может быть вменяемой. А уж надуманные проблемы со спрайтами просто смешат.

**Comment by SpaceBum** [comment]
#109 #
